### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by wdmwhh** [researchmm/TTVSR#2]
How long does it take to train TTVSR using 8 gpus on V100? Around 30 days?

**Comment by wdmwhh** [comment]
I'm sorry to ask another question. What is the gpu memory usage when training TTVSR using 8 gpus on V100?

**Comment by ChengxuLiu** [comment]
In the training, we use the 32G V100. the gpu memory usage exceeds 20G, and the higher memory cost is needed in the testing stage (inference 100 frames). The training time is about half a month.

**Comment by wdmwhh** [comment]
Thanks for you reply. The runtime analysis may be problematic. When comparing _Reconstruction Network_ of TTVSR, 2 shared 60 resblks and upsample, with BasicVSR, 2 non-shared 30 resblks and upsample, the runtime of _Reconstruction Network_ of TTVSR should be longer than that of BasicVSR. However, according to the following table in Supplementary Material, the runtime of _Reconstruction Network_ of TTVSR is less than half that of BasicVSR.
![image](https://user-images.githubusercontent.com/38210459/163674540-677e93c6-5810-449d-b398-c798e2350f4a.png)

**Comment by ChengxuLiu** [comment]
Thank you for your careful reading. We spent some time exploring the reasons for this table.
This is indeed an error in calculating the runtime. This should because we have missing the cuda sync command in the calculation.  Very much appreciate your promptness in pointing out our mistakes. Sorry we have not found the related code to calculate the runtime before, so we recalculated the runtime of this table. The runtime of _Reconstruction Network_ of TTVSR is 72ms. 
We will correct this mistake and update~~
Very sorry for the trouble~
